{"uuid": "e4326ade-8115-44f8-893e-fec05e93abb7", "children": ["75870539-bbdc-4bdd-b90b-97028e27e0fc", "8b663992-e127-42c4-973e-be40f9816653", "ca29e4fa-61e6-4ec6-8244-0493a8b965d5", "856fd16c-f0ab-4e45-b3b7-e4ab256413c6", "88b5b31b-a25c-46a9-8422-379658d211ea", "5e9ac4f5-97eb-4450-a79b-6a3cb3527ce3", "d478539b-ee39-49bd-91d1-46db0233766b", "b838139b-1a50-4da0-ad34-7c36d692b1fa"], "befores": [{"name": "_xunit_setup_class_fixture_TestQuestionAnswers", "status": "broken", "statusDetails": {"message": "TypeError: unsupported callable\n", "trace": "  File \"C:\\Users\\funny\\PycharmProjects\\Sprint_6\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\funny\\PycharmProjects\\Sprint_6\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\funny\\PycharmProjects\\Sprint_6\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\funny\\PycharmProjects\\Sprint_6\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\funny\\PycharmProjects\\Sprint_6\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\funny\\PycharmProjects\\Sprint_6\\venv\\Lib\\site-packages\\_pytest\\python.py\", line 787, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, cls)\n  File \"C:\\Users\\funny\\PycharmProjects\\Sprint_6\\venv\\Lib\\site-packages\\_pytest\\python.py\", line 717, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\funny\\PycharmProjects\\Sprint_6\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 189, in impl\n    params = func_parameters(func, *a, **kw)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\funny\\PycharmProjects\\Sprint_6\\venv\\Lib\\site-packages\\allure_commons\\utils.py\", line 231, in func_parameters\n    arg_spec = inspect.getfullargspec(func)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\funny\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\inspect.py\", line 1394, in getfullargspec\n    raise TypeError('unsupported callable') from ex\n"}, "start": 1726406634309, "stop": 1726406634310}], "start": 1726406634309, "stop": 1726406636875}